// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbksmfmiqvtqdgegaytc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJia3NtZm1pcXZ0cWRnZWdheXRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NjcwNDUsImV4cCI6MjA2NzI0MzA0NX0.GZmyi8yQm7GFrC7o3hWrX-hA_X6FztLujA9bYqzeivE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});